version: '3'
services:

    rabbit:
        image: "rabbitmq:3-management"
        ports:
            - "8080:15672"
            - "5672:5672"
            - "25676:25676"

    mongo-datalake:
        image: "mongo:4"
        ports:
            - "27017:27017"
        environment:
          MONGO_INITDB_DATABASE: "mongo-datalake"

    consumer:
        image: "node:8"
        ports:
            - "3000"
        command: "npm run consumer"
        working_dir: "/usr/src/app"
        volumes:
            - "./:/usr/src/app"
        depends_on:
            - "rabbit"
        environment:
          NODE_PORT: "3000"

    producer:
        image: "node:8"
        ports:
            - "3000"
        command: "npm run producer"
        working_dir: "/usr/src/app"
        volumes:
            - "./:/usr/src/app"
        depends_on:
            - "rabbit"
        environment:
          NODE_PORT: "3000"
