version: '3'
services:

    rabbit:
        image: "rabbitmq:3.8-management"
        ports:
          - "5672"
          - "15672"

    mongo-datalake:
        image: "mongo:4"
        ports:
            - "27017"
        environment:
          MONGO_INITDB_DATABASE: "mongo-datalake"

    haproxy:
        image: "eeacms/haproxy"
        depends_on:
        - "producer"
        ports:
        - "80:5000"
        - "1936:1936"
        environment:
          BACKENDS: "producer"
          DNS_ENABLED: "true"
          LOG_LEVEL: "info"
          STATS_PORT: 1936
          BACKENDS_PORT: 80

    producer:
        image: "node:8"
        working_dir: "/usr/src/app"
        command: "npm run producer"
        volumes:
            - "./:/usr/src/app"
        depends_on:
            - "rabbit"
        ports:
            - "80"
        environment:
          NODE_PORT: "80"

    consumer:
        image: "node:8"
        working_dir: "/usr/src/app"
        command: "npm run consumer"
        volumes:
            - "./:/usr/src/app"
        depends_on:
            - "rabbit"
        ports:
            - "80"
        environment:
          NODE_PORT: "80"
